name = "finance-manager-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

# Worker configuration
[env.production]
name = "finance-manager"

[env.development]
name = "finance-manager-dev"

[env.test]
name = "finance-manager-test"

# Variables
[vars]
ENVIRONMENT = "development"
AUTH_SESSION_DURATION = "7d"
AWS_REGION = "us-east-1"
SES_FROM_EMAIL = "noreply@finance-manager.com"
SES_FROM_NAME = "Finance Manager"

[env.test.vars]
ENVIRONMENT = "test"
JWT_SECRET = "test-jwt-secret-key-for-testing-only"
AUTH_SESSION_DURATION = "1h"
AWS_REGION = "us-east-1"
SES_FROM_EMAIL = "test@finance-manager.com"
SES_FROM_NAME = "Finance Manager Test"

[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "dev-jwt-secret-please-change-in-production-use-strong-random-key"
# JWT_SECRET should be set via secrets in production: wrangler secret put JWT_SECRET
# AUTH_SESSION_DURATION can be set here or via secrets for flexibility
AUTH_SESSION_DURATION = "7d"
AWS_REGION = "us-east-1"
SES_FROM_EMAIL = "noreply@finance-manager.com"
SES_FROM_NAME = "Finance Manager"
# AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY should be set via secrets:
# wrangler secret put AWS_ACCESS_KEY_ID
# wrangler secret put AWS_SECRET_ACCESS_KEY

# D1 Database bindings
[[d1_databases]]
binding = "FINANCE_MANAGER_DB"
database_name = "finance-manager-db"
database_id = "886fa63b-1b70-42bc-8acd-62c21d68e42b"
migrations_dir = "migrations"

# Test D1 Database
[[env.test.d1_databases]]
binding = "FINANCE_MANAGER_DB"
database_name = "test-finance-manager-db"
database_id = "test-db-id"
migrations_dir = "migrations"

# Production D1 Database (separate instance for production)
[[env.production.d1_databases]]
binding = "FINANCE_MANAGER_DB"
database_name = "prod-finance-manager-db"
database_id = "5320fcf4-f13e-441f-8952-e94f8b9cfb1d"
migrations_dir = "migrations"

# KV Storage bindings
[[kv_namespaces]]
binding = "FINANCE_MANAGER_CACHE"
id = "0e0af82b22224048a122082d1f3f6d42"

# Test KV Storage
[[env.test.kv_namespaces]]
binding = "FINANCE_MANAGER_CACHE"
id = "test-kv-id"

# Production KV Storage
[[env.production.kv_namespaces]]
binding = "FINANCE_MANAGER_CACHE"
id = "138dfa25adf345539677e7ef493eb335"

# R2 Storage bindings
[[r2_buckets]]
binding = "FINANCE_MANAGER_DOCUMENTS"
bucket_name = "finance-manager-documents"

# Test R2 Storage
[[env.test.r2_buckets]]
binding = "FINANCE_MANAGER_DOCUMENTS"
bucket_name = "test-finance-manager-documents"

# Production R2 Storage
[[env.production.r2_buckets]]
binding = "FINANCE_MANAGER_DOCUMENTS"
bucket_name = "prod-finance-manager-documents"

# AI bindings for OCR functionality
[env.production.ai]
binding = "AI"



# Vectorize bindings for document embeddings
# [[vectorize]]
# binding = "DOCUMENT_EMBEDDINGS"
# index_name = "finance-manager-documents"

# Test Vectorize
[[env.test.vectorize]]
binding = "DOCUMENT_EMBEDDINGS"
index_name = "test-finance-manager-documents"

# Production Vectorize
[[env.production.vectorize]]
binding = "DOCUMENT_EMBEDDINGS"
index_name = "prod-finance-manager-documents"

# Observability
[observability]
enabled = true

[observability.logs]
enabled = true
