name = "finance-manager"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "finance-manager"
route = { pattern = "finance-manager.irfandimarsya.workers.dev/*", zone_name = "irfandimarsya.workers.dev" }

[env.development]
name = "finance-manager-dev"

# Variables
[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

# D1 Database bindings
[[d1_databases]]
binding = "FINANCE_MANAGER_DB"
database_name = "finance-manager-db"
database_id = "886fa63b-1b70-42bc-8acd-62c21d68e42b"

# KV Storage bindings
[[kv_namespaces]]
binding = "FINANCE_MANAGER_CACHE"
id = "0e0af82b22224048a122082d1f3f6d42"

# R2 Storage bindings
[[r2_buckets]]
binding = "FINANCE_MANAGER_DOCUMENTS"
bucket_name = "finance-manager-documents" 

logpush = true
[observability.logs]
enabled = true
